title: "Pablo Villarejo"
author: "Pablo Villarejo"
description: "Universidad de Málaga"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Holaaa"}
  - {file: "aboutMe.md", title: "Sobre mí"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:p.villarejoperez@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/pablo-villarejo"}
  - {title: LinkedIn, icon: "fab fa-linkedin", url: "https://www.linkedin.com/in/pablo-villarejo/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
